### ISSUE TITLE
有个小问题

### ISSUE THREAD

**Issue by ducyyy** [761133412/AQI-Prediction#1]
你好, Support目录下的support_tcn.py文件是否缺少呢?

**Comment by ducyyy** [comment]
> 你好, Support目录下的support_tcn.py文件是否缺少呢?

Model\model_major.py 文件需要引用

**Comment by lewispony** [comment]
> > 你好, Support目录下的support_tcn.py文件是否缺少呢?
> 
> Model\model_major.py 文件需要引用

你的model_major.py 确实没有support_tcn

**Comment by 761133412** [comment]
support_tcn文件的引用被去掉了，感谢提醒
